### ISSUE TITLE
Change MSMQ Subscription Storage default queue

### ISSUE THREAD

**Issue by dvdstelt** [Particular/NServiceBus.Transport.Msmq#10]
<sup>*Moved from https://github.com/Particular/NServiceBus/issues/4148 opened by @timbussmann on [21 Sep 2016 12:02 UTC](https://github.com/Particular/NServiceBus/issues/4148)*</sup>
When using the MSMQ subscription storage it uses the queue `NServiceBus.Subscriptions` by default (v5-v6). V4 used `{endpointName}.Subscriptions` instead. It seems to make more sense to use a endpoint-specific subscription queue in order to avoid conflicts when running multiple endpoints using MSMQ subscription storage on the same machine.

Some ideas raised by @andreasohlund:

> I think we have to make it mandatory since just changing the default would be a breaking change that would means message loss on upgrade since we'll create a new queue?
> 
> Or could we have the storage check for the existence of a queue called "NServiceBus.Subscriptions" and use that one if present and use the EndpointName.Subscriptions one if not? (think I rather be explicit here)

relates to https://github.com/Particular/NServiceBus/issues/4147

**Comment by ramonsmits** [comment]
I just read this in our docs:

> When using MSMQ Subscription persistence, the default queue to store the subscription messages is NServiceBus.Subscriptions. **It is important to override this queue name for each endpoint to avoid sharing the same subscription queue for different endpoints running on the same machine.**

This is the warning you get at startup:

> WARN  NServiceBus.Features.MsmqSubscriptionPersistence Could not find configuration section for Msmq Subscription Storage and no name was specified for this endpoint. Going to default the subscription queue

That warning doesn't imply at all that every endpoint should have its own subscription queue. 

There is currently a customer that mentions they had a few cases where subscriptions got lost which required restarting publishers and/or subscribers in order for subscribers to receive the events again. 

If sharing the subscription queue among different major NServiceBus versions could lead to loss of subscriptions when publishers restart then that means our default configuration can result in message loss! However, I currently don't understand that we would be vulnerable to this after inspecting the code base.

**Comment by indualagarsamy** [comment]
@dvdstelt - I apologize I didn't see this issue and I had raised a duplicate. But it's now resolved via https://github.com/Particular/NServiceBus.Transport.Msmq/pull/47

Essentially we default to [EndpointName].Subscriptions. 
If we find a queue called "NServiceBus.Subscriptions" we throw an exception asking the user to move the subscriptions to the right queue or provide it via the API.

**Comment by indualagarsamy** [comment]
Relates to https://github.com/Particular/NServiceBus.Transport.Msmq/pull/47
