### ISSUE TITLE
Logs are missleading when no queue name configured for MSMQ sub storage

### ISSUE THREAD

**Issue by dvdstelt** [Particular/NServiceBus.Transport.Msmq#11]
<sup>*Moved from https://github.com/Particular/NServiceBus/issues/4145 opened by @andreasohlund on [20 Sep 2016 18:28 UTC](https://github.com/Particular/NServiceBus/issues/4145)*</sup>
I saw this on the group:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/fLGSWcmeEGE/E4ImM1HGCAAJ

> 09/20/2016 14:31:47 -03:00 [Warning] Could not find configuration section for Msmq Subscription Storage and no name was specified for this endpoint. Going to default the subscription queue

This seems to imply that there is no endpoint name when in this case there is no specific name specified for the storage queue so we default it to `NServiceBus.Subscriptions`

**Comment by andreasohlund** [comment]
We now log a better warning:

https://github.com/Particular/NServiceBus.Transport.Msmq/blob/develop/src/NServiceBus.Transport.Msmq/Persistence/SubscriptionStorage/MsmqSubscriptionPersistence.cs#L17
