### ISSUE TITLE
MSMQ connection strings are not validated

### ISSUE THREAD

**Issue by dvdstelt** [Particular/NServiceBus.Transport.Msmq#13]
<sup>*Moved from https://github.com/Particular/NServiceBus/issues/2510 opened by @johnsimons on [21 Oct 2014 08:01 UTC](https://github.com/Particular/NServiceBus/issues/2510)*</sup>
MSMQ connections strings support the following settings:

```
deadLetter=true/false;
journal=true/false;
cacheSendConnection=true/false;
useTransactionalQueues=true/false;
timeToReachQueue=timespan
```

If the user enters invalid keys and or value we should throw a exception that states what is wrong.

**Comment by janovesk** [comment]
Discussed on sync Sep 27th, 2017.

A new code-first API and killing support for the connection string makes this unnecessary.

Closing
