### ISSUE TITLE
Routing: Prevent mistakes in instance mapping file

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Transport.Msmq#134]
It's possible to configure all sorts of attributes in the instance mapping file for an endpoint instance (e.g. `machine`) but in case an user doesn't exactly use the casing as expected, the transport will not be able to find the attribute (unless it explicitly looks for all possible mutations).

At first glance I see two different implementations:
- Make the schema for the instance mapping file more strict to not allow arbitrary attributes and include the `machine` and `queue` attributes. This will cause exceptions if anything else is configured. In case of runtime changes, this might result in changes not being picked up since after startup validation changes will let the endpoint keep the last known valid mapping configuration. As the instance mapping file is currently limited to MSMQ, there is no more need for the support of arbitrary information in the mapping file.
- Make the lookup to the `EndpointInstances.Properties` property more forgiving so that a lookup for `machine` will also return if the attribute was declared `MACHINE`. This easy to implement by passing  `StringComparer.InvariantCultureIgnoreCase` to a newly created Dictionary.

/cc @bording @SzymonPobiega

**Comment by ramonsmits** [comment]
Backward compatible solution:

- We can extend the XSD with all attributes that we support as a v2 schema
- Check against v2, if good, continue as is, if invalid fall back to current behavior and log a validation warning
- In a next major we can just enforce v2.
