### ISSUE TITLE
Have MSMQ throw if CheckMachineNameForComplianceWithDTCLimitation isn't satisfied

### ISSUE THREAD

**Issue by dvdstelt** [Particular/NServiceBus.Transport.Msmq#14]
<sup>*Moved from https://github.com/Particular/NServiceBus/issues/2132 opened by @johnsimons on [27 May 2014 23:50 UTC](https://github.com/Particular/NServiceBus/issues/2132)*</sup>
If we are to be safe by default for production, shouldn't we be throwing in the `CheckMachineNameForComplianceWithDTCLimitation`, see 

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/CheckMachineNameForComplianceWithDtcLimitation.cs

@andreasohlund @indualagarsamy @SimonCropp thoughts?

**Comment by dvdstelt** [comment]
<sup>*@andreasohlund commented on <a id="issuecomment-257309681" href="14#user-content-issuecomment-257309681">31 Oct 2016 14:33 UTC</a>*</sup>
Do we see this as a breaking change?

**Comment by indualagarsamy** [comment]
I think this can be done similar to the changes that are being done as part of https://github.com/Particular/NServiceBus.Transport.Msmq/pull/35/files
