### ISSUE TITLE
Make MSMQ CircuitBreaker configurable

### ISSUE THREAD

**Issue by dvdstelt** [Particular/NServiceBus.Transport.Msmq#15]
<sup>*Moved from https://github.com/Particular/NServiceBus/issues/2085 opened by @chrisbednarski on [03 May 2014 05:50 UTC](https://github.com/Particular/NServiceBus/issues/2085)*</sup>
from [NServiceBus.SqlServer #7](https://github.com/Particular/NServiceBus.SqlServer/issues/7)

```
<appSettings>
  <add key="NServiceBus/MsmqDequeueStrategy/Threshold" value="100"/>
  <add key="NServiceBus/MsmqDequeueStrategy/ResetEvery" value="00:00:30"/>
</appSettings>
```

related code [here](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/MsmqDequeueStrategy.cs#L363)

**Comment by dvdstelt** [comment]
<sup>*@johnsimons commented on <a id="issuecomment-42097953" href="15#user-content-issuecomment-42097953">03 May 2014 06:44 UTC</a>*</sup>
I'm not convinced we need this for msmq since it is all local

---
<sup>*@chrisbednarski commented on <a id="issuecomment-43189574" href="15#user-content-issuecomment-43189574">15 May 2014 09:47 UTC</a>*</sup>
unless it's running in a virtual environment (eg EBS volume on AWS) and its on a network drive


---
<sup>*@danielmarbach commented on <a id="issuecomment-173130465" href="15#user-content-issuecomment-173130465">20 Jan 2016 08:42 UTC</a>*</sup>
@johnsimons I think @chrisbednarski made a good point and since we implemented it in https://github.com/Particular/NServiceBus.SqlServer/issues/7 shouldn't we align MSMQ as well?


---
<sup>*@andreasohlund commented on <a id="issuecomment-250460844" href="15#user-content-issuecomment-250460844">29 Sep 2016 13:08 UTC</a>*</sup>
If we do this it should be a code first API

`.UseTransport<Msmq>().CircuitBreaker().Bla`


---
<sup>*@danielmarbach commented on <a id="issuecomment-255723277" href="15#user-content-issuecomment-255723277">24 Oct 2016 12:12 UTC</a>*</sup>
This seems to be an additive API we could add to MSMQ only. would this change our viewpoint in terms of future or next minor?


---
<sup>*@bording commented on <a id="issuecomment-255781265" href="15#user-content-issuecomment-255781265">24 Oct 2016 15:52 UTC</a>*</sup>
> If we do this it should be a code first API

👍 v4 of RabbitMQ now has this:

https://docs.particular.net/nservicebus/rabbitmq/connection-settings#controlling-behavior-when-the-broker-connection-is-lost-timetowaitbeforetriggering

**Comment by janovesk** [comment]
This is made irrelevant by https://github.com/Particular/PlatformDevelopment/issues/746.

Closing

**Comment by indualagarsamy** [comment]
@janovesk - can you document the outcome? PlatDev is a private repo. Thanks.
