### ISSUE TITLE
Msmq subscription storage should bind its queue as "receiving"

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Transport.Msmq#18]
<sup>*Moved from https://github.com/Particular/NServiceBus/issues/4153 opened by @andreasohlund on [22 Sep 2016 09:35 UTC](https://github.com/Particular/NServiceBus/issues/4153)*</sup>
Since "receiving" really means that the endpoint "owns" the queue so we should create it.

We currently create the shared queues so this is not something that needs fixing in v6

**Comment by ramonsmits** [comment]
Purge on startup would purge the subscription queue if the queue would be marked as receiving.

Closing as this isn't solving a customer problem and the current solution just works fine.
