### ISSUE TITLE
Clean up the InstanceMappingFileFeature test

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus.Transport.Msmq#24]
>OK, we still have the one InstanceMappingFileFeature test that is commented out for now until we decide if/how to expose the relevant parts externally, but that can be resolved after this is merged.
>
>So, I believe this is ready to be merged!

See: 
https://github.com/Particular/NServiceBus.Transport.Msmq/pull/3#issuecomment-305284731

**Comment by ramonsmits** [comment]
Research is this is still needed.

**Comment by mikeminutillo** [comment]
Could be replaces with this:

```csharp
[Test]
public async Task Should_configure_default_values()
{
    var endpointConfiguration = new EndpointConfiguration("Foo");
    endpointConfiguration.UseTransport<MsmqTransport>();
    endpointConfiguration.SendFailedMessagesTo("error");
    endpointConfiguration.UsePersistence<InMemoryPersistence>();

    await Endpoint.Create(endpointConfiguration);

    var settings = endpointConfiguration.GetSettings();

    Assert.That(settings.Get<Uri>(InstanceMappingFileFeature.PathSettingsKey), Is.EqualTo("instance-mapping.xml"));
    Assert.That(settings.Get<TimeSpan>(InstanceMappingFileFeature.CheckIntervalSettingsKey), Is.EqualTo(TimeSpan.FromSeconds(30)));
}
```

Not sure if there's a lot of value in this test though. Would it be better to test these defaults as a part of a full acceptance test?
