### ISSUE TITLE
Poison message fails to be sent to remote error queue and is retried indefinitely

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Transport.Msmq#26]
When a message has corrupt headers and a remote error queue has been configured the `MovePoisonMessageToErrorQueue` fails which results in the whole operation to be rolled back. **The message is retried indefinitely.**

- This works correctly for local error queues
- Audit forwarding to remote audit queue works correctly.
- Processing errors are correctly moved to the remote error queue
- This is reproduced in an environment of two machines in the same Active Directory

The log message formatting at the following line is suspicious:
- https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Transports/Msmq/ReceiveStrategy.cs#L95

```c#
var error = $"Message '{message.Id}' is classfied as a poison message and will be moved to '{errorQueue.QueueName}'";
```

This is using `errorQueue.QueueName` and different from the way the RecoverabilityExecutor logs the queue as that is based on the configured queue as a string type. This could explain why audit forwarding and regular error processing still works.

```
System.Messaging.MessageQueueException (0x80004005): The specified format name does not support the requested operation. For example, a direct queue format name cannot be deleted.\r\n   at System.Messaging.MessageQueue.GenerateQueueProperties()\r\n   at System.Messaging.MessageQueue.get_QueuePath()\r\n   at System.Messaging.MessageQueue.get_QueueName()\r\n   at NServiceBus.ReceiveStrategy.MovePoisonMessageToErrorQueue(Message message, MessageQueueTransactionType transactionType) in C:\\BuildAgent\\work\\3206e2123f54fce4\\src\\NServiceBus.Core\\Transports\\Msmq\\ReceiveStrategy.cs:line 95\r\n   at NServiceBus.TransactionScopeStrategy.<ReceiveMessage>d__1.MoveNext() in C:\\BuildAgent\\work\\3206e2123f54fce4\\src\\NServiceBus.Core\\Transports\\Msmq\\TransactionScopeStrategy.cs:line 36
```

Error information logged by NServiceBus:
```
2017-06-06 08:46:19.630 WARN  NServiceBus.ReceiveStrategy Message 'b644ac05-920c-42ba-ba3f-4d4777ae7afe\478520848' has corrupted headers
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.MsmqUtilities.DeserializeMessageHeaders(Message m) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqUtilities.cs:line 111
   at NServiceBus.MsmqUtilities.ExtractHeaders(Message msmqMessage) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqUtilities.cs:line 50
   at NServiceBus.ReceiveStrategy.TryExtractHeaders(Message message, Dictionary`2& headers) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\ReceiveStrategy.cs:line 70
```

Error information logged by logging AppDomain.FirstChanceException :
```
2017-06-06 08:46:19.666 DEBUG FirstChanceException Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.MsmqUtilities.DeserializeMessageHeaders(Message m) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MsmqUtilities.cs:line 111
```

Correctly working error logic for normal processing errors:
```
2017-06-06 08:33:06.991 ERROR NServiceBus.RecoverabilityExecutor Moving message '09281c83-7371-4fa5-b59d-a78a006bbc7a' to the error queue 'error@demo.corp.nbraceit.com' because processing failed due to an exception:
```

Corrupt message to reproduce this:

 - [MovePoisonMessageToErrorQueue.zip](https://github.com/Particular/NServiceBus.Transport.Msmq/files/1054074/MovePoisonMessageToErrorQueue.zip)

## References

- https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Transports/Msmq/ReceiveStrategy.cs#L95
- https://github.com/Particular/NServiceBus.Transport.Msmq/blob/develop/src/NServiceBus.Transport.Msmq/ReceiveStrategy.cs#L95
- https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Recoverability/RecoverabilityExecutor.cs#L84

**Comment by ramonsmits** [comment]
I've also reproduced this with V5.

**Comment by ramonsmits** [comment]
Based on https://github.com/Particular/PlatformDevelopment/blob/master/guidelines/triage.md this should be triaged as *Major* bug as when this happens this can cause outages in production as it hangs on the current message. Especially in case of V5 as the maximum concurrency level in V5 is 1. In V6 to get full outage the amount of poison messages in the endpoint queue must be equal or higher then the configured maximum concurrency level.

**Comment by ramonsmits** [comment]
@dennis and I have confirmed that the send operations works fine. It is only the `.QueueName` property which fails. If we use `.Path` or `.FormatName` then either of these works fine. 

Do we want to:

- include this information here in the MSMQ syntax (FormatName:DIRECT=OS:DEMO\private$\error)
- include this information in our syntax (error@ZOLDER)
- only say *forwarded to the configured error queue*

**Comment by dvdstelt** [comment]
Better be safe than sorry, I vote for the 3rd option.

**Comment by andreasohlund** [comment]
I'd say option 3 for the patch. Then we can consider the others for the fix for 1.0.0

**Comment by dennis** [comment]
@ramonsmits When you use @dennis, i get notified and auto-subscribed to this issue. Just so you know

**Comment by ramonsmits** [comment]
Sorry @dennis for pulling you into this mess :-)

**Comment by andreasohlund** [comment]
@dvdstelt can you verify that this is fixed on develop as well? (I know we have patched the core MSMQ version )

**Comment by dvdstelt** [comment]
@andreasohlund I can verify, but it will take me quite some time. I currently have one VM running on an Active Directory domain, but I'd have to bring two up and running and then try to recreate the scenario. Was this already confirmed by Ramon or do we want another layer to verify this?

**Comment by indualagarsamy** [comment]
@andreasohlund @dvdstelt - I have verified that the develop branch has the right code that was patched on the NSB support branch, which is fixing the typo and also removing the error queue name from the log. I am closing this issue. Please reopen if you think otherwise.
