### ISSUE TITLE
Make MSMQ substorage the default?

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Transport.Msmq#27]
Now that the transport is a external opt-in package should we consider making the msmq substorage the default for subscriptions?

I guess to be full "storage self sufficient" we would need native timeouts as well

**Comment by indualagarsamy** [comment]
Even for a majority of customers using MSMQ as the transport, MSMQ is not the default choice for subscription storage or timeouts. I don't think we should default to MSMQ for subscription storage just to make it self sufficient. Storage is based on user requirements and should require some thought and the user should explicitly select it.

**Comment by andreasohlund** [comment]
Should we introduce a more intuitive api?

`.UseTransport<MsmqTransport>().SubscriptionStorage<Msmq>()` ?

**Comment by dvdstelt** [comment]
If we decide to have native timeouts, would it then again have to change in
```
.UseTransport<MsmqTransport>();
.UsePersistence<MsmqPersistence>();
```
and have `.SubscriptionStorage<Msmq>()` deprecated again?

I haven't 100% followed the discussions around native timeouts in MSMQ, but the suggested solution look like we are abusing MSMQ and DLQ for native timeouts. Just because it's possible, doesn't mean we should use it. So in that case I'd definitely be for your suggestion, @andreasohlund

**Comment by andreasohlund** [comment]
>If we decide to have native timeouts, would it then again have to change in

I don't think that would change anything?

`.UseTransport<MsmqTransport>().SubscriptionStorage<MsmqQueue>()` is still valid even with native timeouts?

This also show that we should try to find a way for transports to have mandatory config options. I think this will be solved once we figure out how to make transport, serializer etc mandatory settings from a core perspective.

Eg.

```
var busConfig = new BusConfigration(new MsmqTransport(Substorage.Msmq, ...), new JsonDotNetSerializer());

var endpointConfig = new EndpointConfiguration("sales",busConfig);
```

This would allow eg. rabbit to require a connection string while MSMQ would need that.

```
var busConfig = new BusConfiguration(new RabbitMq("Some connection string"), new JsonDotNetSerializer());

var endpointConfig = new BusConfiguration("sales",busConfig);
```
@Particular/nservicebus-maintainers fyi

**Comment by andreasohlund** [comment]
This isn't relevant until we decided if we should push the entire message driven pubsub feature into MSMQ (since it would be the only user once SQL gets native pubsub)

@Particular/aws-maintainers right now SQS needs this as well but there are plans to go with a native SNS impl?

Closing this

**Comment by mauroservienti** [comment]
> @Particular/aws-maintainers right now SQS needs this as well but there are plans to go with a native SNS impl?

yes, the main issue IIRC is that SNS is an additional cost, so we might end up with both options, we haven't discussed this yet, just made a note that we want it.
