### ISSUE TITLE
MSMQ support in net standard/core

### ISSUE THREAD

**Issue by sumantfordev** [Particular/NServiceBus.Transport.Msmq#280]
Although i understand MSMQ libraries are not available in .net core /standard , However there are people who have ported MSMQ/system messaging to .net standard

https://github.com/weloytty/MSMQ.Messaging

This is particularly seems to be still active. Can this be leveraged  to port this Nservicebus msmq library to net core. 

Even if i have to do a manual build, what would be the way? Sorry i am new,  but we have legacy apps that want to port to .net core running in windows and continue leveraging msmq before we can switch to other message brokers.

**Comment by DavidBoike** [comment]
Hi Sumant,

We have no plans to do that. We go a little further into the details in [a section of our MSMQ is dead blog post](https://particular.net/blog/msmq-is-dead#But-what-about-open-source) but I think the biggest is that it's not a drop-in replacement becuase .NET Core does not have distributed transactions.
