### ISSUE TITLE
Override default MSMQ header serializer to reduce the size of the MSMQ headers

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Transport.Msmq#32]
The MSMQ transport an XML serializer to write the header data. This results in quite a heavy impact on the overall messages size. Some customers choose a different message serializer to get smaller messages but that only applies to the message body.

## Example

Using protobuf I could make a pretty normal message with 2 properties, an additional collection with one item and this was serialized as 26 bytes. However, our headers are 1,787 bytes!!

We have the following options to reduce the header size. 

- Compression
- Different format, for example http header like collections, or similar to an ini file, or even other formats like http/2 HPACK
- Not writing unneeded headers
- Formatting values differently
- Shorten keys
- Different headers
- Combining headers
- Smarter headers

I've compared header sizes for regular messages and messages forwarded to the audit queue.

| type    | format |  size | compressed | diff |
| ------- | ------ | ----: | ---------: | ---: |
| audit   | xml    | 2,481 |        586 |  23% |
| message | xml    | 1,787 |        526 |  29% |
| audit   | http   | 1,026 |        442 |  43% |
| audit   | ini    |   840 |        435 |  51% |
| message | http   |   745 |        403 |  54% |
| message | ini    |   633 |        403 |  63% |

We can probably even switch to binary formatters.

```
interface IMsmqHeaderSerializer
{
    byte[] Serialize(Dictionary<string,string> values);
    Dictionary<string,string> values Deserialize(byte[] extension);
}

var transport = endpointConfiguration.UseTransport<MsmqTransport>()
transport.UseCustomHeaderSerializer(new CompressingBinarySerializer());
```

## Compression

Only applying compressing the header byte[] saves 70% for regular message on the header size!

## Different format

A drawback of compression is that the data isn't readable. Using a http header (59%) or ini (65%) like format can reduce the size.
An example of an ini like format:

```ini
[NServiceBus]
MessageId:f721b027-631b-4f81-a0bf-a7c200d03f0a
MessageIntent:Send
ReplyToAddress:_testqueue@ZOLDER
CorrelationId:f721b027-631b-4f81-a0bf-a7c200d03f0a
OriginatingMachine:ZOLDER
OriginatingEndpoint:_testqueue
ContentType:protobuf
EnclosedMessageTypes:PubSubTroughputTesterv6.DeviceStatusChanged, PubSubTroughputTesterv6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
ConversationId:f67c247d-d2bf-4d64-9c08-a7c200d03f0a
Version:6.3.4
TimeSent:2017-08-01 12:38:12:084215 Z
ProcessingStarted:2017-08-01 12:38:12:085719 Z
ProcessingEnded:2017-08-01 12:38:12:085719 Z
ProcessingMachine:ZOLDER
ProcessingEndpoint:_testqueue
[$.diagnostics]
originating.hostid:9b9a656959aecd352da31b9a80d9ad4a
hostid:9b9a656959aecd352da31b9a80d9ad4a
hostdisplayname:ZOLDER
[]
CorrId:f721b027-631b-4f81-a0bf-a7c200d03f0a\0
```

## Not writing unneeded headers

There is both the `CorrId` and `CorrelationId` headers. One of them is for backward compatibility but likely not needed for most environments.

## Value formatting

- Guids could be formatted as base64 strings
- Guids could be formatted without dashes
- Timestamps could be written as milliseconds since epoch (`2017-08-01 12:38:12:085719 Z` [28] vs `1501593186029` [13])

## Shorten keys

- MessageId => Id
- MessageIntent = > Intent
- ReplyToAddress => ReplyTo
- ProcessingStarted -> Start

## Different headers

- ProcessingEnded => Duration: 1200 *(microseconds)*

## Combining headers

A lot of headers are always written in pairs:

- ProcessingStarted:2017-08-01 12:38:12:085719 Z
- ProcessingEnded:2017-08-01 12:38:12:085719 Z
- ProcessingMachine:ZOLDER
- ProcessingEndpoint:_testqueue

$.diagnostics.originating.hostid:9b9a656959aecd352da31b9a80d9ad4a
$.diagnostics.hostid:9b9a656959aecd352da31b9a80d9ad4a
$.diagnostics.hostdisplayname:ZOLDER

Combined:

- Processing: _testqueue; machine=zolder; start=2017-08-01 12:38:12:085719 Z; duration=0
-$.diagnostics: 

## Smarter headers

For example, the reply to address, is on the same machine. This doesn't need the machine name postfix.

ReplyToAddress:_testqueue@ZOLDER

ReplyToAddress:_testqueue

## Potential improved headers

The following is 591 bytes, representing the same information as the original XML header of 1,787 bytes without any compression.

```
[NServiceBus]
Id:f721b027631b4f81a0bfa7c200d03f0a
ConversationId:f67c247dd2bf4d649c08a7c200d03f0a
Intent:Send
ReplyTo:_testqueue
OriginatingEndpoint:_testqueue
ContentType:protobuf
EnclosedMessageTypes:PubSubTroughputTesterv6.DeviceStatusChanged, PubSubTroughputTesterv6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Version:6.3.4
TimeSent:2017-08-01 12:38:12:084215 Z
Processing: _testqueue;host=zolder;start=2017-08-01 12:38:12:085719;duration=0
[$.diagnostics]
originating.hostid:9b9a656959aecd352da31b9a80d9ad4a
hostid:9b9a656959aecd352da31b9a80d9ad4a;host=ZOLDER
```

**Comment by bording** [comment]
Looking at some of the options you've proposed here, I don't think it makes sense for an individual transport to do most of these things. Altering the headers, removing headers, changing the format are all things that should probably be handled by Core instead, and have some pretty serious wire-compatibility considerations.

If you change how you're you're handling headers, then it has to be opt-in because it will break any endpoint that hasn't been upgraded.

Adding a way to choose a different serializer does seem like a good idea. It would be an opt-in option to choose something other than XML, and it's up to the users to deploy it in a way that keeps their messages readable.

You could even take it a step further, and allow an endpoint to receive messages in more than one format as a first step, and have another API that changes the serializer used for outgoing messages.

**Comment by ramonsmits** [comment]
> pretty serious wire-compatibility considerations.

That is why I added the explicit configuration of a different serializer:

    var transport = endpointConfiguration.UseTransport<MsmqTransport>()
    transport.UseCustomHeaderSerializer(new CompressingBinarySerializer());

I currently have a spike that does MSMQ header compression, the decompression checks if the first two bytes of the headers byte are the gzip header signature. It works very well and is backward compatible during a receive. However, the header data would just need to be slimmed down even further. I also liked 

I also noticed this PR by @Scooletz https://github.com/Particular/NServiceBus/pull/4802 which is also focused on reducing the headers byte[] by using a binary format with well-known header keys. Really interesting approach and would also be implementable if we would have an overrideable header serializer for at least the MSMQ transport.

It is similar to an idea I had to just md5 all header keys to make them 16 bytes as most header keys have the `NServiceBus.` prefix as 12 characters/bytes space waisted but using byte or short for well-known keys is even better.

Another issue is that all values are stored as text, this makes it really hard to create a size efficient header serializer. A lot could be gained by serializing time stamps as longs and keys which are often guids or hashes as byte arrays. We could have a mapper that is smart enough to be type aware but that would require to parse the string into a binary value while it was already converted to a string when added to the header collection. Maybe we would need to make the header collection

**Comment by Scooletz** [comment]
Thank you for mentioning my PR @ramonsmits ❤️ There was another one, based on writing a custom XML backward compatible serializer https://github.com/Particular/NServiceBus/pull/3895 I closed it as a result of this comment/reasoning https://github.com/Particular/NServiceBus/pull/3895#issuecomment-231889788 Maybe, current core maintainers would reconsider this idea (which was backward compatible).

**Comment by ramonsmits** [comment]
As said, my reasoning was. I wanted to try out protobuf as the body serializer but still got massive messages.

- Don't add an NServiceBus ID, rely on the transport generated ID. If the message fails, then during error forwarding add the current transport ID as the NServiceBus ID. This would only work reliably with MSDTC and AtomicSendsWithReceive.
- Don't add `ReplyToAddress` on an event
   - `ReplyToAddress=_testqueue.in@ZOLDER` saves in this at least 35, but 117 bytes when not present in the XML.
- EnclosedMessageTypes redux, only use a message name, maybe rename it to 'topic'
   - `EnclosedMessageTypes=PubSubTroughputTesterv6.DeviceStatusChanged, PubSubTroughputTesterv6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null` [145]
   - `Topic=DeviceStatusChanged` [25] saves 120 chars in this example

Anyway, it is clear that a lot can be done to save space. I don't think we must focus on a specific implementation but that we should decide if we want to add the extendability.

**Comment by ramonsmits** [comment]
We could:

1. Add an opt-in compression method.
2. Add an extension point.

We agree that the current mechanism that generates headers as an XML document is inefficient as well as how the header keys are structured but that this is not solving a customer problem. As the transport is EOL and any changes in header format also would require updates with ServiceControl we decided this is not worth the effort.
