### ISSUE TITLE
Use wildcard in packages.config

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Transport.Msmq#39]
https://github.com/Particular/NServiceBus.Transport.Msmq/pull/38#issuecomment-326224949

Use preleases wildcard in packages config just as https://github.com/Particular/NServiceBus.Callbacks/pull/75

**Comment by indualagarsamy** [comment]
Fixed by https://github.com/Particular/NServiceBus.Transport.Msmq/pull/40
