### ISSUE TITLE
Should throw an exception if the machine name exceeds NETBIOS limitation instead of just warn

### ISSUE THREAD

**Issue by dvdstelt** [Particular/NServiceBus.Transport.Msmq#4]
<sup>*Moved from https://github.com/Particular/NServiceBus/issues/4660 opened by @indualagarsamy on [03 May 2017 16:33 UTC](https://github.com/Particular/NServiceBus/issues/4660)*</sup>
Currently we do check for the NetBios limitation here:
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/CheckMachineNameForComplianceWithDtcLimitation.cs#L29

However, having an non-compliant machine name could result in problems with messages being sent and has resulted in support cases where the NETBios name was the problem. 

Instead of just logging a warning, should we throw instead?

**Comment by dvdstelt** [comment]
<sup>*@indualagarsamy commented on <a id="issuecomment-298965114" href="4#user-content-issuecomment-298965114">03 May 2017 16:34 UTC</a>*</sup>
cc / @Particular/msmq-transport-maintainers 

---
<sup>*@dvdstelt commented on <a id="issuecomment-298998647" href="4#user-content-issuecomment-298998647">03 May 2017 18:38 UTC</a>*</sup>
As I stated in Slack, a customer says it can reproduce a situation where NServiceBus crashes and then the queue gets corrupt!
Not sure if we can reproduce this, but if customer can and there's just the slightest chance of queues getting corrupt, I agree with @indualagarsamy and think we should throw.

**Comment by indualagarsamy** [comment]
Fixed via https://github.com/Particular/NServiceBus.Transport.Msmq/pull/37

**Comment by indualagarsamy** [comment]
More details on this issue can be found on this duplicate issue: https://github.com/Particular/NServiceBus.Transport.Msmq/issues/14
