### ISSUE TITLE
Should we support useTransactionalQueues=false but transaction mode is NOT set to None?

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Transport.Msmq#43]
- useTransactionalQueues=false
- transaction mode is default
- endpoint queue is transactional

The endpoint will just start which is strange as it can send non-transactional messages while the receives are transactional.

**Comment by janovesk** [comment]
Discussed on sync Sep 27th 2017. 

Closing this since we have the longterm goal of removing support for non-transactional sends in MSMQ completely.
