### ISSUE TITLE
WIP: cacheSendConnection default value not set if specifying a connection string without this parameter

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Transport.Msmq#53]

**Comment by andreasohlund** [comment]
ah, so that would explain the perf drop you saw?

**Comment by ramonsmits** [comment]
@andreasohlund It seems it was purely random that adding `cacheSendConnection=True` resolved the issue. 

After a quick code inspection it also seems that the default is correctly set if specifying a connection string but without the `cacheSendConnection` argument:

https://github.com/Particular/NServiceBus.Transport.Msmq/blob/60204a962ffe6f1fe7671654408b26d72192fdf0/src/NServiceBus.Transport.Msmq/MsmqSettings.cs#L11

https://github.com/Particular/NServiceBus.Transport.Msmq/blob/60204a962ffe6f1fe7671654408b26d72192fdf0/src/NServiceBus.Transport.Msmq/MsmqConnectionStringBuilder.cs#L27-L30

Closing it.
