### ISSUE TITLE
NServiceBus.Transport.Msmq not available for netstandard2.0

### ISSUE THREAD

**Issue by maxs-s** [Particular/NServiceBus.Transport.Msmq#537]
Hi guys.

I am currently working on the old project and want to update some old stuff and packages from .NET 4.7 to netstandart 2.0.  One of the dependency is the NServiceBus.Transport.Msmq. The problem that I do not see netstandart 2.0 support in visual studio
![VS-missing](https://user-images.githubusercontent.com/26608609/212115948-5d387ed9-71f9-4dbc-82e4-e2a79c7afd7e.png)

Although it looks available in Nuget feed
 
![nuget-msmq](https://user-images.githubusercontent.com/26608609/212116353-45ede88d-b761-425c-833d-34ab28903e35.png)

What I am doing wrong?

Thanks in advance

**Comment by bording** [comment]
Hi @maxs-s 

That nuget.org page is inaccurate/misleading. The MSMQ transport package targets .NET Framework, and always has. This is because that MSMQ itself is only supported on .NET Framework.

**Comment by maxs-s** [comment]
thank you very much
