### ISSUE TITLE
Would having `RouteToThisMachine` make sense?

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Transport.Msmq#57]
We currently have `RouteToThisInstance` and `RouteToThisEndpoint`. When you use the distributor or sender side distribution I can image there are situations where want a certain message flow to be sticky. First of all, consequtive steps are all on the same box, no network hops required to continue to the next step, second, this creates the ability to potentially make better use of storage. Instead of the need to store process data in a central location, you could have processing all done locally scattered over multiple steps.

For example, you want to work on a BLOB, which has multiple sequential conversion steps.

It would be nice to have a `RouteToThisMachine` to make such processing possible.

**Comment by andreasohlund** [comment]
Discussed on the sync and we concluded that this is such and edge case that we're unlikely to implement this. Closing for now
