### ISSUE TITLE
Would you consider targeting netcore also if a compatibility pack was available ?

### ISSUE THREAD

**Issue by valeriob** [Particular/NServiceBus.Transport.Msmq#58]

**Comment by andreasohlund** [comment]
@valeriob yes we would definitely consider this.

@bording I remember that you mentioned some rumors that MS was going to release a MSMQ compat pack, do you have a link?

**Comment by bording** [comment]
I asked about this when I first saw the Windows Compatibility Pack design issue: 

https://github.com/dotnet/designs/pull/16#issuecomment-339810350
https://github.com/dotnet/designs/pull/16#issuecomment-339811057

And it looks like that is being tracked here: https://github.com/dotnet/corefx/issues/6204

**Comment by DavidBoike** [comment]
Closing, as Microsoft has indicated they are done porting .NET Framework APIs to .NET Core. See https://particular.net/blog/msmq-is-dead
