### ISSUE TITLE
Help needed - Experimental MSMQ Transport for .net Core

### ISSUE THREAD

**Issue by endeffects** [Particular/NServiceBus.Transport.Msmq#73]
I've started to work on a msmq support for .net core.
I'd like to invite you to help me to get it working:

https://github.com/endeffects/NServiceBus.Transport.Msmq/

**Comment by andreasohlund** [comment]
>This issue probably should be in our MSMQ repository.

I've moved the issue

**Comment by endeffects** [comment]
> MSMQ is only available on Windows so why not just run with .NET framework?

Well, the Performance of ASP.NetCore is much better than the "old" .net Framework Version.
So why should we stay? Also most of the available Transport Options of NServiceBus
are expensive, tricky or "slow". So i preffer Msmq to get things done.

>  Why take a dependency on an experimental unofficial library?

For the namespaces of the experimental library i had to include the implementation into the msmq transport project. Also there is currently no official implementation scheduled.

**Comment by andreasohlund** [comment]
I've subscribed to the repo and happy to help you out when time permits so feel free to ping me for PR reviews over there, closing this for now

**Comment by jpactor** [comment]
> This issue probably should be in our MSMQ repository.
> 
> What I don't understand is why this is needed? What is the benefit?
> 
> MSMQ is only available on Windows so why not just run with .NET framework? Why take a dependency on an experimental unofficial library?

Because, especially now, net6 is going to be the new standard for .NET going forward. Please consider making available a net6.0-windows release of this package.

**Comment by Fabjooo** [comment]
Ran into the same problem, would be nice if there was .NET 6 compatibility :)
