### ISSUE TITLE
Spike native delayed delivery for MSMQ

### ISSUE THREAD

**Issue by dvdstelt** [Particular/NServiceBus.Transport.Msmq#8]
<sup>*Moved from https://github.com/Particular/NServiceBus/issues/4443 opened by @timbussmann on [25 Jan 2017 17:13 UTC](https://github.com/Particular/NServiceBus/issues/4443)*</sup>
@SzymonPobiega [found a potential solution / hidden MSMQ feature](https://github.com/Particular/NServiceBus/issues/4223#issuecomment-272166132) which could allow us to do native delayed delivery and avoiding the TimeoutManager.

## Original Comment from Szymon on #4223 describing the solution

It turns out WCF has always had a way to specify a custom dead letter queue, per contract. It turned out (via dotPeek) that this is done on a per-message level in MSMQ, via property number 67/68:

```
message.TimeToBeReceived = TimeSpan.FromDays(1000);
setUI1.Invoke(newProps, new object[] { 7, (byte)1 }); //Enable dead letter
var buffer = StringToBytes(deadLetter);
setString.Invoke(newProps, new object[] { 67, buffer });
setUI4.Invoke(newProps, new object[] { 68, deadLetter.Length });
queue.Send(message, MessageQueueTransactionType.Single);
```

We the message sent in the way above will come back to the dead letter queue in 1000 days (I verified that for lower values obviously). The only limitation is, the dead letter queue has to be local so you can't have a centralized one (out of the box). That said, we can easily create an endpoint whose only purpose would be receiving messages and putting them in a local centralized timeout queue to wait for their due date.

## PoA
* [ ] Verify this approach works reliably for NSB users using MSMQ transport
* [ ] Identify limitations
* [ ] Identify migration scenarios
* [ ] Assess potential risks (e.g. relying on undocumented features)
* [ ] Decide for go / nogo

**Comment by dvdstelt** [comment]
<sup>*@SzymonPobiega commented on <a id="issuecomment-275310462" href="8#user-content-issuecomment-275310462">26 Jan 2017 05:23 UTC</a>*</sup>
One thing: this feature is documented (e.g. [here](https://msdn.microsoft.com/en-us/library/aa368234(v=vs.85).aspx)). It is not exposed via `System.Messaging` abstraction.

**Comment by weralabaj** [comment]
Few limitations of custom DLQs, that we need to take into account when designing solution:

1. The message will be moved to the **system** DLQ in the following events:
- The specified DLQ is full when the QM attempts to deliver the NACK message to it. => **Optimal queue size needs to be considered.**
- The sending application does not have sufficient permissions to write to the specified DLQ. => **If the endpoint will write to the local endpoint-specific queue probably there won't be a problem? Anything to consider in queue creation scripts?**
- The specified DLQ does not exist. => **Proper installation/upgrade guide.**
- The specified DLQ is not transactional. => **As above.**

**Comment by SzymonPobiega** [comment]
Well, since the queue used as DLQ will be local endpoint's input queue I think some of the problems are already handled by existing checks. But we need to verify.

**Comment by ramonsmits** [comment]
What when the endpoint has been migrated to another host? What about scaled out endpoints? What about elastic scaling? I'm not sure we really want to abuse the application-specific dead letter queue behavior for this.

**Comment by ramonsmits** [comment]
Considering the transport is more or less EOL and this is not solving problem we don't see a reason to implement it.
